### ISSUE TITLE
RPA Hive Regression (Dependent to Open Commitments)

### ISSUE THREAD

**Issue by mbharathm** [beezlabs-org/l3-support#18]
There has been changes made to RPA Hive in the benefit of Open Commitments automation. So the impact of this RPA change has to be tested with other RPA automation scenarios.

**Comment by mbharathm** [comment]
Open Commitments go-Live is dependent with RPA Hive upgrade on Production Bacardi

**Comment by kruthik-nivas** [comment]
Open commitments have been tested with a new set of credentials from the factory side and have been handed over to consultants

**Comment by mbharathm** [comment]
This is obsolete after we changed the approach to ADLS in open commitments.

**Comment by mbharathm** [comment]
This task is obsolete as the approach for open commitments has changed to Azure data lake and no RPA Hive upgrade is needed.
