### ISSUE TITLE
Credit Release Japan - Currency Fix

### ISSUE THREAD

**Issue by mbharathm** [beezlabs-org/l3-support#22]

**Comment by mbharathm** [comment]
@ARUNASALAVADIVU , please mention the SysAid ticket number in the task for reference.

**Comment by ARUNASALAVADIVU** [comment]
> 

2725080 - No task in group for credit release japan

**Comment by mbharathm** [comment]
CAR document shared, ready for deployment.

**Comment by ARUNASALAVADIVU** [comment]
Profiles assigned, refer to the email attached and notes
Closed the ticket # 2725080

**Comment by ARUNASALAVADIVU** [comment]
Issue is under testing by end user.

**Comment by ARUNASALAVADIVU** [comment]
2725080 - ticket closed
