### ISSUE TITLE
Client Secret Update for Azure OAuth Credentials

### ISSUE THREAD

**Issue by ARUNASALAVADIVU** [beezlabs-org/l3-support#27]

**Comment by ARUNASALAVADIVU** [comment]
SysAid Number - 2728238

Hi Team,

Creating this Sysaid ticket to make update in Production Tulip with respect to Client Secret for Azure OAuth Credentials. The update is going to be done with respect to Azure identities configured for the following automations.


  1.  GTR Dashboard Automation
  2.  Volume Report Automation
  3.  Overtime Report Automation
  4.  Prodiver Automation

Azure Identity Names to be updated:

1. azure-blob-rpa,
2.AzureAuthIdentity

Thanks and Regards,
Sakthivel

**Comment by mbharathm** [comment]
This is created and updated for all dependent bots. Old secret was deleted.
