### ISSUE TITLE
Metro Production Deployment

### ISSUE THREAD

**Issue by ARUNASALAVADIVU** [beezlabs-org/l3-support#29]
SysAid Number - 2612743

Hi Team,

Creating a Sysaid Ticket for Metro Production Deployment.

Regards,
Sakthivel

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Sakthi1502** [comment]
Update 29/05/2023: Waiting for Lissa to provide UAT Signoff to move the solution to Production. Have done a follow up today as well. cc: @mbm-hub @swapnamn @ARUNASALAVADIVU

**Comment by mbharathm** [comment]
Production deployment is completed
