### ISSUE TITLE
BOA File Automation Workflow

### ISSUE THREAD

**Issue by ARUNASALAVADIVU** [beezlabs-org/l3-support#3]
Failure Bot: BOA File Automation
Bot Message: Bot Execution failed Timed out after 120 seconds
Automation will run on daily basis @01.00pm. Failure happening more than a month. we tried to pause the automation till the issue got resolved. It is not getting updated in job schedule. Please help in pausing this until a permanent fix can be found.
![BOA](https://user-images.githubusercontent.com/118357931/206101907-791ab33d-21ca-44de-af84-6f9ab65a1370.png)

**Comment by Sathraja-Beez** [comment]
Waiting for the budget approval from the clients

**Comment by mbharathm** [comment]
![Image](https://github.com/beezlabs-org/l3-support/assets/64949233/83243c83-7232-4efe-9ff3-3f85c36688a6)

This would have been checked with the customer before taking up the fix. @Sakthi1502 . Caution for further issues.
@swapnamn , please have a checkpoint on long pending tickets with customers before being taken up.
