### ISSUE TITLE
Issue Feb MEC - MJE Pending Approvals report

### ISSUE THREAD

**Issue by ARUNASALAVADIVU** [beezlabs-org/l3-support#31]
SysAid Number - 2694598

Hello Fer, Luis Diego,
     After reviewing the MJE Pending report execution for the 8PM run I see that there is an issue starting on that run that the email is not being executed successfully. The image below shows the latest executions, both scheduled and ad-hoc runs but it is filing since 8PM.
    As per our conversation, please proceed to use the My Reports option to extract the open/pending MJE reports.

    Apologies for the inconvenience.

[cid:image002.png@01D94D48.A9754800]

    The pending approvals extracton is working as expected, failure happens in the email sending bot.
   After some review I believe the issue is that the API call to extract the list returns an empty list (0 pending approvals) and hence the email execution can’t find the data to send. Will review with the team early tomorrow.

[cid:image003.png@01D94D48.F12EA3D0]

Pura vida,
[cid:image001.png@01D94D48.3CC94DF0]

**Comment by mbharathm** [comment]
This is tracked in a separate issue and closed
