### ISSUE TITLE
Credit Block Release Automation with multilevel approval Portugal WF1 - 2624886

### ISSUE THREAD

**Issue by ARUNASALAVADIVU** [beezlabs-org/l3-support#40]
SysAid Number -  2624886

Workflow: Credit Block Release Automation with multilevel approval Portugal WF1

Bot: Vkm4 - Sale order filter bot Portugal

Bot Message: Bot execution failed due to : For input string: "139.40

Creating SysAid for Credit Block Release Automation with multilevel approval Portugal WF1 got failure in tulip execution.

**Comment by swapnamn** [comment]
Closed the issue as the user has not responded back with checking the negative scenarios.
