### ISSUE TITLE
Canada SAQ SO Automation - Issue

### ISSUE THREAD

**Issue by mbharathm** [beezlabs-org/l3-support#51]
SysAid Number - 2619139

Creating as a SysAid ticket

Best Regrads,
P.ARUNA
Beezlabs HelpDesk

________________________________
From: EXT_Bharath Mahesh <b@bacardi.com>
Sent: Thursday, December 1, 2022 10:40 AM
To: Jean-Jaurice Ndihokubwayo <jndihokubw@bacardi.com>; dbaskaran <dbaskaran1@bacardi.com>
Cc: Juan Solano Rojas <jsolanor@bacardi.com>; BeezLabs Help Desk <helpdesk@beezlabs.com>; Paola Moreira Abarca <pmoreiraa@bacardi.com>
Subject: Re: 5TH REQUEST; URGENT Canada SAQ SO Automation

Copying Helpdesk team + Paola to the mail chain.

-------------

Best Regards,

Bharath,

Delivery Head,

Beez Innovation Labs (BeezLabs),

Mobile.: +91 6379903588

Location: India. (GMT+5:30)

--------------

Know more about Bacardi Automation Services<https://bacardi.sharepoint.com/sites/BacardiAutomationServicesBAS>

[signature_2687667207]<https://bacardi.sharepoint.com/sites/BacardiAutomationServicesBAS>

From: Jean-Jaurice Ndihokubwayo <jndihokubw@bacardi.com>
Date: Thursday, 1 December 2022 at 01:22
To: EXT_Dinesh Baskaran <dbaskaran1@bacardi.com>
Cc: EXT_Bharath Mahesh <b@bacardi.com>, EXT_Muthuvijayan ilanchelian <milanchelian@bacardi.com>, Juan Solano Rojas <jsolanor@bacardi.com>
Subject: RE: 5TH REQUEST; URGENT Canada SAQ SO Automation

Hello guys,

We have run into issues with the automation again, there is 2 orders in Backo 5 that aren’t being transmitted into SAP.

[cid:image003.png@01D904CB.594B4E80]

Thanks

JEAN-JAURICE NDIHOKUBWAYO

Demand Planner • Supply & Logistics, BACARDI CANADA INC.

5524 St. Patrick, Suite 400 Montreal, Quebec H4E 1A8

C: 514 476-6479 | E: jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>

[cid:image001.jpg@01D904CB.527546B0]

From: EXT_Dinesh Baskaran <dbaskaran1@bacardi.com>
Sent: June 9, 2022 2:51 AM
To: Jean-Jaurice Ndihokubwayo <jndihokubw@bacardi.com>
Cc: EXT_Bharath Mahesh <b@bacardi.com>; EXT_Muthuvijayan ilanchelian <milanchelian@bacardi.com>; CAONT_canadab2b <canadab2b@bacardi.com>; Adriana Espinel <aespinel@Bacardi.com>; Juan Solano Rojas <jsolanor@bacardi.com>
Subject: Re: 5TH REQUEST; URGENT Canada SAQ SO Automation

Hello team,

Hope you are doing great!

We monitored the last execution of SAQ automation, and it is successful. Automation has picked up 9 orders from the portal and 8 new orders got created successfully in SAP.

Regards,

Dinesh Baskaran

________________________________

From: Jean-Jaurice Ndihokubwayo <jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>>
Sent: Wednesday, June 8, 2022, 23:12
To: Adriana Espinel <aespinel@Bacardi.com<mailto:aespinel@Bacardi.com>>; EXT_Dinesh Baskaran <dbaskaran1@bacardi.com<mailto:dbaskaran1@bacardi.com>>; Juan Solano Rojas <jsolanor@bacardi.com<mailto:jsolanor@bacardi.com>>
Cc: EXT_Bharath Mahesh <b@bacardi.com<mailto:b@bacardi.com>>; EXT_Muthuvijayan ilanchelian <milanchelian@bacardi.com<mailto:milanchelian@bacardi.com>>; CAONT_canadab2b <canadab2b@bacardi.com<mailto:canadab2b@bacardi.com>>
Subject: RE: 5TH REQUEST; URGENT Canada SAQ SO Automation

Thank you team i really appreciate your help.

We’ll keep the new contacts in mind for the future.

JEAN-JAURICE NDIHOKUBWAYO

Inventory Planner • Supply & Logistics, BACARDI CANADA INC.

5524 St. Patrick, Suite 400 Montreal, Quebec H4E 1A8

C: 514 476-6479 | E: jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>

[cid:image001.jpg@01D904CB.527546B0]

From: Adriana Espinel <aespinel@Bacardi.com<mailto:aespinel@Bacardi.com>>
Sent: June 8, 2022 1:10 PM
To: EXT_Dinesh Baskaran <dbaskaran1@bacardi.com<mailto:dbaskaran1@bacardi.com>>; Juan Solano Rojas <jsolanor@bacardi.com<mailto:jsolanor@bacardi.com>>; Jean-Jaurice Ndihokubwayo <jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>>
Cc: EXT_Bharath Mahesh <b@bacardi.com<mailto:b@bacardi.com>>; EXT_Muthuvijayan ilanchelian <milanchelian@bacardi.com<mailto:milanchelian@bacardi.com>>; CAONT_canadab2b <canadab2b@bacardi.com<mailto:canadab2b@bacardi.com>>
Subject: RE: 5TH REQUEST; URGENT Canada SAQ SO Automation

Thank you, dear all for your prompt response to this request.

@JJ<mailto:jndihokubw@bacardi.com>, please bear in mind the email address and process shared by Juan to get needed and timely support in case of any new issues.  Thank you.

In the future, please address any issues to

rpatools@bacardi.com<mailto:rpatools@bacardi.com> (this raises a ticket automatically)

bassupport@bacardi.com<mailto:bassupport@bacardi.com> (the overall support team for Bacardi Automation Services)

jsolanor@bacardi.com<mailto:jsolanor@bacardi.com> (for visibility, or chat with me through teams to escalate any issues)

Kind regards,

------------------------------------
Adriana Espinel
Operations – Supply Chain Integration
Mobile: + 1 305-505-1648

CONFIDENTIALITY NOTE.  This message (including any attachments) may contain information that is privileged, confidential or otherwise protected from disclosure. If you are not the intended recipient, please immediately advise the sender by reply email that this message has been inadvertently transmitted to you and delete this email, any attachments, and all copies from your system.  Thank you for your cooperation.

From: EXT_Dinesh Baskaran <dbaskaran1@bacardi.com<mailto:dbaskaran1@bacardi.com>>
Sent: Wednesday, June 8, 2022 1:03 PM
To: Adriana Espinel <aespinel@Bacardi.com<mailto:aespinel@Bacardi.com>>; Juan Solano Rojas <jsolanor@bacardi.com<mailto:jsolanor@bacardi.com>>; Jean-Jaurice Ndihokubwayo <jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>>
Cc: EXT_Bharath Mahesh <b@bacardi.com<mailto:b@bacardi.com>>; EXT_Muthuvijayan ilanchelian <milanchelian@bacardi.com<mailto:milanchelian@bacardi.com>>; CAONT_canadab2b <canadab2b@bacardi.com<mailto:canadab2b@bacardi.com>>
Subject: Re: 5TH REQUEST; URGENT Canada SAQ SO Automation

Hello Team,

The issue has been resolved and coming executions will pick up the orders. Kindly let me know if you face any issues.

Sorry for the late response. We understood

from the mail chain that the issue has been sent to recipients who are not part of the current support team. Please mail to bassupport@bacardi.com<mailto:bassupport@bacardi.com>, if you face any issue in future

Have a great day!

Regards,

Dinesh Baskaran

________________________________

From: Adriana Espinel <aespinel@Bacardi.com<mailto:aespinel@Bacardi.com>>
Sent: Wednesday, June 8, 2022, 20:23
To: Juan Solano Rojas <jsolanor@bacardi.com<mailto:jsolanor@bacardi.com>>; Jean-Jaurice Ndihokubwayo <jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>>; EXT_Pawan Ojha <pojha@bacardi.com<mailto:pojha@bacardi.com>>; EXT_Deepak Ram <dram@bacardi.com<mailto:dram@bacardi.com>>; EXT_Amit Chowdhary <achowdhary@bacardi.com<mailto:achowdhary@bacardi.com>>; EXT_Muthuvijayan ilanchelian <milanchelian@bacardi.com<mailto:milanchelian@bacardi.com>>; EXT_Dinesh Baskaran <dbaskaran1@bacardi.com<mailto:dbaskaran1@bacardi.com>>
Subject: RE: 5TH REQUEST; URGENT Canada SAQ SO Automation

Thank you, for your prompt response, dear Juan.

Kind regards,

------------------------------------
Adriana Espinel
Operations – Supply Chain Integration
Mobile: + 1 305-505-1648

CONFIDENTIALITY NOTE.  This message (including any attachments) may contain information that is privileged, confidential or otherwise protected from disclosure. If you are not the intended recipient, please immediately advise the sender by reply email that this message has been inadvertently transmitted to you and delete this email, any attachments, and all copies from your system.  Thank you for your cooperation.

From: Juan Solano Rojas <jsolanor@bacardi.com<mailto:jsolanor@bacardi.com>>
Sent: Wednesday, June 8, 2022 10:44 AM
To: Adriana Espinel <aespinel@Bacardi.com<mailto:aespinel@Bacardi.com>>; Jean-Jaurice Ndihokubwayo <jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>>; EXT_Pawan Ojha <pojha@bacardi.com<mailto:pojha@bacardi.com>>; EXT_Deepak Ram <dram@bacardi.com<mailto:dram@bacardi.com>>; EXT_Amit Chowdhary <achowdhary@bacardi.com<mailto:achowdhary@bacardi.com>>; EXT_Muthuvijayan ilanchelian <milanchelian@bacardi.com<mailto:milanchelian@bacardi.com>>; EXT_Dinesh Baskaran <dbaskaran1@bacardi.com<mailto:dbaskaran1@bacardi.com>>
Subject: RE: 5TH REQUEST; URGENT Canada SAQ SO Automation

Hello Jean-Jaurice, Adriana,

    Apologies, the team has been on an offsite this week and probably went under the radar. We’re looking at it right now. Will update you back in an hour.

    In the future, please address any issues to

rpatools@bacardi.com<mailto:rpatools@bacardi.com> (this raises a ticket automatically)

bassupport@bacardi.com<mailto:bassupport@bacardi.com> (the overall support team for Bacardi Automation Services)

jsolanor@bacardi.com<mailto:jsolanor@bacardi.com> (for visibility, or chat with me through teams to escalate any issues)

Pura vida,

[cid:image002.png@01D904CB.527546B0]

From: Adriana Espinel <aespinel@Bacardi.com<mailto:aespinel@Bacardi.com>>
Sent: Wednesday, June 8, 2022 8:15 AM
To: Jean-Jaurice Ndihokubwayo <jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>>; EXT_Pawan Ojha <pojha@bacardi.com<mailto:pojha@bacardi.com>>; EXT_Deepak Ram <dram@bacardi.com<mailto:dram@bacardi.com>>; EXT_Amit Chowdhary <achowdhary@bacardi.com<mailto:achowdhary@bacardi.com>>; EXT_Muthuvijayan ilanchelian <milanchelian@bacardi.com<mailto:milanchelian@bacardi.com>>; EXT_Dinesh Baskaran <dbaskaran1@bacardi.com<mailto:dbaskaran1@bacardi.com>>
Cc: Juan Solano Rojas <jsolanor@bacardi.com<mailto:jsolanor@bacardi.com>>
Subject: RE: 5TH REQUEST; URGENT Canada SAQ SO Automation

Hello, JJ,

Including Juan- for his support.  Dear Juan, are you aware of any issues with these BOTs?  Please advise.  Thank you.

Kind regards,

------------------------------------
Adriana Espinel
Operations – Supply Chain Integration
Mobile: + 1 305-505-1648

CONFIDENTIALITY NOTE.  This message (including any attachments) may contain information that is privileged, confidential or otherwise protected from disclosure. If you are not the intended recipient, please immediately advise the sender by reply email that this message has been inadvertently transmitted to you and delete this email, any attachments, and all copies from your system.  Thank you for your cooperation.

From: Jean-Jaurice Ndihokubwayo <jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>>
Sent: Wednesday, June 8, 2022 10:09 AM
To: EXT_Pawan Ojha <pojha@bacardi.com<mailto:pojha@bacardi.com>>; EXT_Deepak Ram <dram@bacardi.com<mailto:dram@bacardi.com>>; EXT_Amit Chowdhary <achowdhary@bacardi.com<mailto:achowdhary@bacardi.com>>; EXT_Muthuvijayan ilanchelian <milanchelian@bacardi.com<mailto:milanchelian@bacardi.com>>; Adriana Espinel <aespinel@Bacardi.com<mailto:aespinel@Bacardi.com>>; EXT_Dinesh Baskaran <dbaskaran1@bacardi.com<mailto:dbaskaran1@bacardi.com>>
Subject: RE: 5TH REQUEST; URGENT Canada SAQ SO Automation
Importance: High

Hello,

Can i please get a response concerning the automation error? We have a lot of orders that are not being transmitted to SAP and this is causing me to have to create everything manually.

Looping in @Adriana Espinel<mailto:aespinel@Bacardi.com>, Hello Adri, if you know anyone who could help with this please let me know as I’ve been trying since last week and still haven’t gotten an answer.

Thank you

JEAN-JAURICE NDIHOKUBWAYO

Inventory Planner • Supply & Logistics, BACARDI CANADA INC.

5524 St. Patrick, Suite 400 Montreal, Quebec H4E 1A8

C: 514 476-6479 | E: jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>

[cid:image001.jpg@01D904CB.527546B0]

From: Jean-Jaurice Ndihokubwayo
Sent: June 6, 2022 2:59 PM
To: EXT_Pawan Ojha <pojha@bacardi.com<mailto:pojha@bacardi.com>>; EXT_Deepak Ram <dram@bacardi.com<mailto:dram@bacardi.com>>; EXT_Amit Chowdhary <achowdhary@bacardi.com<mailto:achowdhary@bacardi.com>>; EXT_Muthuvijayan ilanchelian <milanchelian@bacardi.com<mailto:milanchelian@bacardi.com>>
Subject: 4TH REQUEST; URGENT Canada SAQ SO Automation
Importance: High

Hello All,

It has now been a week and I haven’T received no feedback from you guys. Please advise.

Thanks

JEAN-JAURICE NDIHOKUBWAYO

Inventory Planner • Supply & Logistics, BACARDI CANADA INC.

5524 St. Patrick, Suite 400 Montreal, Quebec H4E 1A8

C: 514 476-6479 | E: jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>

[cid:image001.jpg@01D904CB.527546B0]

From: Jean-Jaurice Ndihokubwayo
Sent: June 3, 2022 9:42 AM
To: EXT_Pawan Ojha <pojha@bacardi.com<mailto:pojha@bacardi.com>>; EXT_Deepak Ram <dram@bacardi.com<mailto:dram@bacardi.com>>; EXT_Amit Chowdhary <achowdhary@bacardi.com<mailto:achowdhary@bacardi.com>>
Subject: URGENT Canada SAQ SO Automation
Importance: High

Guys,

Please someone advise on the below.

JEAN-JAURICE NDIHOKUBWAYO

Inventory Planner • Supply & Logistics, BACARDI CANADA INC.

5524 St. Patrick, Suite 400 Montreal, Quebec H4E 1A8

C: 514 476-6479 | E: jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>

[cid:image001.jpg@01D904CB.527546B0]

From: Jean-Jaurice Ndihokubwayo
Sent: June 1, 2022 8:51 AM
To: EXT_Pawan Ojha <pojha@bacardi.com<mailto:pojha@bacardi.com>>; EXT_Deepak Ram <dram@bacardi.com<mailto:dram@bacardi.com>>; EXT_Amit Chowdhary <achowdhary@bacardi.com<mailto:achowdhary@bacardi.com>>
Subject: RE: Canada SAQ SO Automation
Importance: High

Team,

This is disrupting a lot of our activities. Please advise asap.

Thanks

JEAN-JAURICE NDIHOKUBWAYO

Inventory Planner • Supply & Logistics, BACARDI CANADA INC.

5524 St. Patrick, Suite 400 Montreal, Quebec H4E 1A8

C: 514 476-6479 | E: jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>

[cid:image001.jpg@01D904CB.527546B0]

From: Jean-Jaurice Ndihokubwayo
Sent: May 31, 2022 9:40 AM
To: Tulip RPA <tulip01@bacardi.com<mailto:tulip01@bacardi.com>>; CAONT_canadab2b <canadab2b@bacardi.com<mailto:canadab2b@bacardi.com>>; EXT_Deepak Ram <dram@bacardi.com<mailto:dram@bacardi.com>>; EXT_Pawan Ojha <pojha@bacardi.com<mailto:pojha@bacardi.com>>; EXT_Amit Chowdhary <achowdhary@bacardi.com<mailto:achowdhary@bacardi.com>>
Subject: RE: Canada SAQ SO Automation
Importance: High

Following up on this, any news?

JEAN-JAURICE NDIHOKUBWAYO

Inventory Planner • Supply & Logistics, BACARDI CANADA INC.

5524 St. Patrick, Suite 400 Montreal, Quebec H4E 1A8

C: 514 476-6479 | E: jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>

[cid:image001.jpg@01D904CB.527546B0]

From: Jean-Jaurice Ndihokubwayo
Sent: May 27, 2022 2:17 PM
To: Tulip RPA <tulip01@bacardi.com<mailto:tulip01@bacardi.com>>; CAONT_canadab2b <canadab2b@bacardi.com<mailto:canadab2b@bacardi.com>>; EXT_Deepak Ram <dram@bacardi.com<mailto:dram@bacardi.com>>; EXT_Pawan Ojha <pojha@bacardi.com<mailto:pojha@bacardi.com>>; EXT_Amit Chowdhary <achowdhary@bacardi.com<mailto:achowdhary@bacardi.com>>
Subject: RE: Canada SAQ SO Automation

Hello team,

Orders are not being picked up by the tulip. Can you please investigate?

Thanks

JEAN-JAURICE NDIHOKUBWAYO

Inventory Planner • Supply & Logistics, BACARDI CANADA INC.

5524 St. Patrick, Suite 400 Montreal, Quebec H4E 1A8

C: 514 476-6479 | E: jndihokubw@bacardi.com<mailto:jndihokubw@bacardi.com>

[cid:image001.jpg@01D904CB.527546B0]

From: Tulip RPA <tulip01@bacardi.com<mailto:tulip01@bacardi.com>>
Sent: May 27, 2022 2:01 PM
To: CAONT_canadab2b <canadab2b@bacardi.com<mailto:canadab2b@bacardi.com>>
Cc: EXT_Deepak Ram <dram@bacardi.com<mailto:dram@bacardi.com>>; EXT_Pawan Ojha <pojha@bacardi.com<mailto:pojha@bacardi.com>>; EXT_Amit Chowdhary <achowdhary@bacardi.com<mailto:achowdhary@bacardi.com>>
Subject: Canada SAQ SO Automation

Dear User,

Exception raised during Direct Login in SAQ portal. Please find the details below:

session not created: This version of ChromeDriver only supports Chrome version 97 Current browser version is 81.0.4044.138 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe (SessionNotCreated)

Regards,
Tulip

**Comment by ARUNASALAVADIVU** [comment]
Closed #2619139
