### ISSUE TITLE
ZDUMMY data mismatch issue

### ISSUE THREAD

**Issue by ARUNASALAVADIVU** [beezlabs-org/l3-support#52]
SysAid Number - 2755185

Sending issue to SysAid.

From: Jose Andres Chaves Porras <jchavesp@bacardi.com>
Date: Friday, 19 May 2023 at 21:56
To: EXT_Avva Chandra Koushik <akoushik@bacardi.com>, David Alberto Solis Villalobos <dsolisv@bacardi.com>, Sergio Rodriguez Sequeira <srodriguezs@bacardi.com>, EXT_Bharath Mahesh <b@bacardi.com>
Cc: Luis Diego Ulate Moran <lulatem@bacardi.com>, Juan Solano Rojas <jsolanor@bacardi.com>, Maria Fernanda Arrieta Siles <mfarrieta@bacardi.com>, Karla Munoz Quesada <krmunozq@bacardi.com>, Melissa Gamboa Calderon <mdgamboac@bacardi.com>, Karen Vega Hidalgo <kvegah@bacardi.com>, Albin Chinchilla Barboza <achinchillab@bacardi.com>, EXT_Mario Dominic <mdominic1@bacardi.com>, Paola Moreira Abarca <pmoreiraa@bacardi.com>
Subject: RE: ZDUMMY UAT Results - ER #2710332
Hello team –

We were able to perform the first run from our side and test the data validity. In the enclosed file you can see the detail of the discrepancies we found in each tab named after each company code with issues.

In addition, we are going to further review internally company code 5478 since this is the first time we see open ZDUMMY balances in this entity.

@EXT_Avva Chandra Koushik<mailto:akoushik@bacardi.com>, can you please help us reviewing these results?

Thanks!

**Comment by mbharathm** [comment]
The ticket can be closed @ARUNASALAVADIVU  @swapnamn as this issue is deployed to Production on last week.

**Comment by mbharathm** [comment]
Reopening as Output Analysis is pending with Production data. A new incident to be created if any issue is identified

**Comment by ARUNASALAVADIVU** [comment]
Ticket Closed
