### ISSUE TITLE
Web scraping Wave1 Issue (GTR / UK)

### ISSUE THREAD

**Issue by ARUNASALAVADIVU** [beezlabs-org/l3-support#53]
SysAid Number - 2753351

Please be informed that we encountered an issue with the loading of Web Scraping Wave 1,. Upon further checking,  there’s been an issue, with the source files which were: WorldDutyFree_05-01-23_16.12.csv and WorldDutyFree_04-01-23_03.00.csv.

**Comment by swapnamn** [comment]
Resolved after pushing the requested files with changes
