### ISSUE TITLE
Email Send Scenarios - Upgrading the approach

### ISSUE THREAD

**Issue by mbharathm** [beezlabs-org/l3-support#54]
- [x] SAQ Email Bot
- [x] Oceans A
- [x] MJE Pending Approval
- [x] Oceans Part B Reconciliation
- [x] Credit Release mail when order is not released
- [x] Prodiver emails
- [x] SGWS Pricing Bot
- [ ] Task Kill API Bot
- [x] CFIN A&P
- [x] Payroll ADP

**Comment by mbharathm** [comment]
Update on May 30

- SAQ - LIVE
- Oceans TA - Ready for Deployment
- Oceans Part B Reconciliation - Ready for deployment
- Credit Release mail when order is not released - In Progress (Rohit)
- Prodiver emails - To be done, repos were identified by May 30
- SGWS Pricing Bot - In Testing and bug was identified last week, Ranjan completed the fix by May 29
- Task Kill API Bot - To be done, repo are yet to be identified, bot code is not there
- CFIN A&P - To be done
- Payroll ADP - To be done

**Comment by ARUNASALAVADIVU** [comment]
2768077 - Ticket closed
