### ISSUE TITLE
Crawler Support Fixes - November

### ISSUE THREAD

**Issue by Sakthi1502** [beezlabs-org/l3-support#76]

**Comment by Sakthi1502** [comment]
Team, please refer the following link for the fixes that need to be taken. I have mentioned the fixes to be checked by developer under the column "Consultant check" https://azurebeezlabs.sharepoint.com/:x:/s/BeezLibrary/EXbjnxQkw6NKqaFwj1ph7g4B5JIUHyXWzTWpa3qit0HrHg?e=5bCxJY

**Comment by koushik-ac** [comment]
11 Issues have been identified for Crawler Fixes. Assigned to @NaveenKumarD8 .

**Comment by koushik-ac** [comment]
ETA - 21/11/2023. Will try to fast track this.

**Comment by NaveenKumarD8** [comment]
4/11 issues Completed.

**Comment by Sakthi1502** [comment]
@NaveenKumarD8 You can refer the below doc links to validate the output data 

Dart-Priority1 Fixes -https://azurebeezlabs.sharepoint.com/:w:/s/BeezLibrary/Edn58FL8zXFAgsWFO0gb77gBnxNgRVVbSQ0J7SeKWnAy3g?e=AwXAUA

PTC Fixes - https://azurebeezlabs.sharepoint.com/:w:/s/BeezLibrary/EVRsQ8vl62RMtWhc3Bj6MzEBEyd54YQHtrsm-yBHLZ5D-A?e=AHxIUw

**Comment by NaveenKumarD8** [comment]
6/11 issues Completed.

**Comment by NaveenKumarD8** [comment]
8/11 issues Completed.
Qualityliquor issue.
1.All the Selectors were changed.
2.After changing the selectors it shows null. The bot was built using html agility it doesn't work now, we have to change that into selenium.
Qualityliquor is considered as an enhancement.

**Comment by NaveenKumarD8** [comment]
9/11 issues completed.

**Comment by NaveenKumarD8** [comment]
10/11 issues were Completed.

**Comment by NaveenKumarD8** [comment]
All issues were completed.
