### ISSUE TITLE
Crawler Support Fixes - December

### ISSUE THREAD

**Issue by Sakthi1502** [beezlabs-org/l3-support#79]

**Comment by Sakthi1502** [comment]
Team, Please find the support issues to be fixed for the month of December. I will provide an update if there are any further fixes that need to be taken.

[December_Report.xlsx](https://github.com/beezlabs-org/l3-support/files/13632130/December_Report.xlsx)

**Comment by Sakthi1502** [comment]
Please find the below docs for PTC to validate the data generated. https://azurebeezlabs.sharepoint.com/:w:/s/BeezLibrary/EVRsQ8vl62RMtWhc3Bj6MzEBEyd54YQHtrsm-yBHLZ5D-A?e=AHxIUw

**Comment by NaveenKumarD8** [comment]
2/4 issues were Completed.

**Comment by SanthoshKumar2220** [comment]
2/3  issues will complete by EOD

**Comment by SanthoshKumar2220** [comment]
Issues are completed which are all assigned for me.

**Comment by NaveenKumarD8** [comment]
All the issues which was assigned to me Completed.
